// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {json} from '../models';

export function GetNotes():Promise<string>;

export function SaveNoteListState(arg1:json.RawMessage):Promise<void>;
